version: '3.8'
services:

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - ${WEBSITE_EXPOSED_PORT}:${NGINX_FRONT_PORT}
    environment:
      - REACT_APP_URL=${APP_URL}
      - BACKEND_API_PORT=${BACKEND_API_PORT}
      - NGINX_FRONT_PORT=${NGINX_FRONT_PORT}

  backend:
    depends_on:
      - postgres
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - ${BACKEND_API_PORT}:${BACKEND_API_PORT}
    environment:
      - HASH_ROUNDS=${HASH_ROUNDS}
      - APP_NAME=${APP_NAME}
      - APP_URL=${APP_URL}
      - BACKEND_API_PORT=${BACKEND_API_PORT}
      - AUTH_42_OAUTH_URL=${AUTH_42_OAUTH_URL}
      - AUTH_42_RETURN_URI=${AUTH_42_RETURN_URI}
      - AUTH_42_CLIENT_KEY=${AUTH_42_CLIENT_KEY}
      - AUTH_42_SECRET_KEY=${AUTH_42_SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - POSTGRES_DB_HOST=${POSTGRES_DB_HOST}
      - POSTGRES_DB_PORT=${POSTGRES_DB_PORT}
      - POSTGRES_DB_USER=${POSTGRES_DB_USER}
      - POSTGRES_DB_PASS=${POSTGRES_DB_PASS}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}

  postgres:
    image: postgres:14.1
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASS}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  name: null
