# Utiliser une image PostgreSQL
FROM postgres:latest

# Configurer les variables d'environnement nécessaires
ENV POSTGRES_DB=transcendance
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password

# Exposer le port que PostgreSQL utilisera
EXPOSE 5432

